---
- hosts: localhost
  gather_facts: no
  vars:
    source_host: 130.61.202.0
    source_path: C:\TeamCity\buildAgent\work\6628867807ab0dac\WindowsService\bin
    target_host: 130.61.154.172
    target_path: C:\deploy
  tasks:
    - name: Transfer folder from source to local machine
      win_copy:
        src: "//{{ source_host }}/{{ source_path }}/"
        dest: "/tmp/"
        force: yes
      delegate_to: localhost

    - name: Transfer folder from local machine to target
      win_copy:
        src: "/tmp/{{ source_path | basename }}/"
        dest: "//{{ target_host }}/{{ target_path }}/"
        force: yes
      delegate_to: localhost

    - name: Remove local folder
      file:
        path: "/tmp/{{ source_path | basename }}/"
        state: absent
