---
- name: Copy files and folders
  hosts: Buildhost
  gather_facts: no

  tasks:
    - name: Copy files and folders
      win_copy:
        src: C:\TeamCity\buildAgent\work\6628867807ab0dac\WindowsService\bin
        dest: C:\deploy
      delegate_to: Deployhost
